In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
X[:,[0, 1]] = X[:,[1, 0]]
print(X[0:10,:])

[['France' 619 'Female' 42 2 0.0 1 1 1 101348.88]
 ['Spain' 608 'Female' 41 1 83807.86 1 0 1 112542.58]
 ['France' 502 'Female' 42 8 159660.8 3 1 0 113931.57]
 ['France' 699 'Female' 39 1 0.0 2 0 0 93826.63]
 ['Spain' 850 'Female' 43 2 125510.82 1 1 1 79084.1]
 ['Spain' 645 'Male' 44 8 113755.78 2 1 0 149756.71]
 ['France' 822 'Male' 50 7 0.0 2 1 1 10062.8]
 ['Germany' 376 'Female' 29 4 115046.74 4 1 0 119346.88]
 ['France' 501 'Male' 44 4 142051.07 2 0 1 74940.5]
 ['France' 684 'Male' 27 2 134603.88 1 1 1 71725.73]]


In [2]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 0] = labelencoder_X_1.fit_transform(X[:, 0])
print(X[0:10,:])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
print(X[0:10,:])
from sklearn.compose import make_column_transformer
preprocessor = make_column_transformer( (OneHotEncoder(),[0]),
                                       remainder="passthrough")
# print(X[0:10,:])
X = preprocessor.fit_transform(X)
X = X[:,1:]
print(X[0:10,:])
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[0 619 'Female' 42 2 0.0 1 1 1 101348.88]
 [2 608 'Female' 41 1 83807.86 1 0 1 112542.58]
 [0 502 'Female' 42 8 159660.8 3 1 0 113931.57]
 [0 699 'Female' 39 1 0.0 2 0 0 93826.63]
 [2 850 'Female' 43 2 125510.82 1 1 1 79084.1]
 [2 645 'Male' 44 8 113755.78 2 1 0 149756.71]
 [0 822 'Male' 50 7 0.0 2 1 1 10062.8]
 [1 376 'Female' 29 4 115046.74 4 1 0 119346.88]
 [0 501 'Male' 44 4 142051.07 2 0 1 74940.5]
 [0 684 'Male' 27 2 134603.88 1 1 1 71725.73]]
[[0 619 0 42 2 0.0 1 1 1 101348.88]
 [2 608 0 41 1 83807.86 1 0 1 112542.58]
 [0 502 0 42 8 159660.8 3 1 0 113931.57]
 [0 699 0 39 1 0.0 2 0 0 93826.63]
 [2 850 0 43 2 125510.82 1 1 1 79084.1]
 [2 645 1 44 8 113755.78 2 1 0 149756.71]
 [0 822 1 50 7 0.0 2 1 1 10062.8]
 [1 376 0 29 4 115046.74 4 1 0 119346.88]
 [0 501 1 44 4 142051.07 2 0 1 74940.5]
 [0 684 1 27 2 134603.88 1 1 1 71725.73]]
[[0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [0.0 0.0 699 0 

In [3]:
# X[0:10,:]


In [4]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [6]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 10)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





8000/8000 [==============================] - 5s 598us/step - loss: 0.4832 - acc: 0.7960
Epoch 2/10
8000/8000 [==============================] - 2s 264us/step - loss: 0.4294 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 2s 257us/step - loss: 0.4244 - acc: 0.7960
Epoch 4/10
8000/8000 [==============================] - 2s 254us/step - loss: 0.4198 - acc: 0.8136
Epoch 5/10
8000/8000 [==============================] - 2s 262us/step - loss: 0.4163 - acc: 0.8271
Epoch 6/10
8000/8000 [==============================] - 2s 261us/step - loss: 0.4143 - acc: 0.8295
Epoch 7/10
8000/8000 [==============================] - 2s 260us/step - loss: 0.4125 - acc: 0.8310
Epoch 8/10
8000/8000 [==============================] - 2s 263us/step - loss: 0.4113 - acc: 0.8317
Epoch 9/10
8000/8000 [==============================] - 2s 280us/step - loss: 0.4099 - acc: 0.8320
Ep

In [9]:
#Model persistance is important. Next time we want to make a prediction we save a model to a file and use that file for predictions.
import joblib
joblib.dump(classifier, 'mlbrain_10.joblib')

['mlbrain_10.joblib']

In [4]:
# #Load our model
# import joblib
# classifier = joblib.load('mlbrain.joblib')

In [13]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

NameError: name 'classifier' is not defined

In [9]:
(cm[0,0]+cm[1,1])/sum(sum(cm))

0.8405

In [5]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

['/job:localhost/replica:0/task:0/device:GPU:0']

In [7]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16054852247229417654
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 27171521167
locality {
  bus_id: 1
  links {
  }
}
incarnation: 6120128759108058327
physical_device_desc: "device: 0, name: Quadro GV100, pci bus id: 0000:01:00.0, compute capability: 7.0"
]


In [5]:
import tensorflow as tf
tf.test.is_gpu_available()

True

In [1]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

Using TensorFlow backend.


['/job:localhost/replica:0/task:0/device:GPU:0']